### PR TITLE
가끔씩 일정의 정렬이 이상해지는 버그 수정

### LINKED ISSUE #213: 월달력 재생성 때 일정 위치가 랜덤하게 꺠지는 버그
## 진행 상황(option)
- [ ] 월달력 재생성 때 일정 위치가 랜덤하게 꺠지는 버그

### PR DESCRIPTION
**Pull request by PsPLoG**
## what is this pr

Resolved: #213 
## Changes

- 일정 정렬이 이상해지는 버그 수정

### 원인
- 코루틴 적용으로 인한 비동기 이슈
```kotlin
val scheduleListContainer = arrayOfNulls<TextView>(SCHEDULE_CONTAINER_SIZE)
          filteredScheduleList.forEach {
              val isFirstShowSchedule = item.date == it.startDate.toLocalDate() || item.dayType == DayType.SUNDAY
              val paddingKey = "${adapterPosition / CALENDAR_COLUMN_SIZE}:${it.id}"
              val paddingLineIndex = lineIndex[paddingKey] //이전 일정이 존재하지만 null이 나와 빈자리를 찾는 것이 원인

              if (paddingLineIndex != null) { // null이 아니면 이전 일정과 이어지도록 index를 찾아 일정 배치 
                  scheduleListContainer[paddingLineIndex] = mappingScheduleTextView(it, isFirstShowSchedule)
              } else { 
                  for (i in scheduleListContainer.indices) { // null 이면 빈자리를 찾아서 일정 배치
                      if (scheduleListContainer[i] == null) {
                          scheduleListContainer[i] = mappingScheduleTextView(it, isFirstShowSchedule)
                          lineIndex[paddingKey] = i
                          break
                      }
                  }
              }
          }
```
정상적인 동작에서는 lineIndex[paddingKey]에서 이전에 존재하는 일정의 위치를 찾아 가야 하지만
이전에 일정이 존재함에도 lineIndex[paddingKey] null이 나오는 현상 발생

원인은 성능 향상을 위해 적용한 코루틴이였다.
```kotlin
CoroutineScope(Dispatchers.Default).launch {
    val scheduleContainer = makePaddingScheduleList(item, schedules)
    val hasAnySchedule = scheduleContainer.any { it != null }
    if (hasAnySchedule) {
        withContext(Dispatchers.Main) {
            binding.layoutMonthSchedule.removeAllViews()
            scheduleContainer.map { it ?: makeDefaultScheduleTextView() }
                .forEach {
                    binding.layoutMonthSchedule.addView(it)
                }
        }
    }
}
```
일정이 처음 위치를 잡게 될 때 lineIndex에 값을 저장하지만 아래 로직이 코루틴을 통해 background 에서 진행되고, lineIndex에 값을 저장하기 전에 

다음 날짜의 로직이 먼저 실행되어 비동기 이슈가 발생
```kotlin
if (scheduleListContainer[i] == null) {
    scheduleListContainer[i] = mappingScheduleTextView(it, isFirstShowSchedule)
    lineIndex[paddingKey] = i
    break
}
```

결론적으로 이전에 진행한 테스트 결과와 버그로 인해  코루틴 적용이 성능 향상에 큰 도음이 안된다고 판단, **코루틴을 제거 했습니다.** 

#### 이전 테스트 결과  (단위 1000ms)
- 코루틴 적용
2021-11-16 17:56:59.481 9801-9801/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:56:59.481 9801-9801/com.drunkenboys.calendarun E/end: 17
2021-11-16 17:56:59.481 9801-9801/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:56:59.481 9801-9801/com.drunkenboys.calendarun E/end: 16
2021-11-16 17:56:59.481 9801-9801/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:56:59.481 9801-9801/com.drunkenboys.calendarun E/end: 15
2021-11-16 17:56:59.525 9801-10346/com.drunkenboys.calendarun E/end_Month: 44
2021-11-16 17:56:59.564 9801-10346/com.drunkenboys.calendarun E/end_Month: 83
2021-11-16 17:56:59.600 9801-10347/com.drunkenboys.calendarun E/end_Month: 119
2021-11-16 17:57:01.583 9801-9801/com.drunkenboys.calendarun E/start: pageAdapter
2021-11-16 17:57:01.584 9801-9801/com.drunkenboys.calendarun E/start: pageAdapter
2021-11-16 17:57:01.585 9801-9801/com.drunkenboys.calendarun E/start: pageAdapter
2021-11-16 17:57:01.599 9801-9801/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:57:01.599 9801-9801/com.drunkenboys.calendarun E/end: 16
2021-11-16 17:57:01.600 9801-9801/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:57:01.600 9801-9801/com.drunkenboys.calendarun E/end: 15
2021-11-16 17:57:01.600 9801-9801/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:57:01.600 9801-9801/com.drunkenboys.calendarun E/end: 16
2021-11-16 17:57:01.636 9801-10346/com.drunkenboys.calendarun E/end_Month: 36
2021-11-16 17:57:01.670 9801-10348/com.drunkenboys.calendarun E/end_Month: 71
2021-11-16 17:57:01.721 9801-10348/com.drunkenboys.calendarun E/end_Month: 121
5:58
- 코루틴 미적용
2021-11-16 17:58:24.857 9964-9964/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:58:24.857 9964-9964/com.drunkenboys.calendarun E/end: 27
2021-11-16 17:58:24.857 9964-9964/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:58:24.857 9964-9964/com.drunkenboys.calendarun E/end: 25
2021-11-16 17:58:24.857 9964-9964/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:58:24.858 9964-9964/com.drunkenboys.calendarun E/end: 25
2021-11-16 17:58:24.910 9964-9964/com.drunkenboys.calendarun E/end_Month: 53
2021-11-16 17:58:24.952 9964-9964/com.drunkenboys.calendarun E/end_Month: 95
2021-11-16 17:58:24.998 9964-9964/com.drunkenboys.calendarun E/end_Month: 141
2021-11-16 17:58:26.100 9964-9964/com.drunkenboys.calendarun E/start: pageAdapter
2021-11-16 17:58:26.101 9964-9964/com.drunkenboys.calendarun E/start: pageAdapter
2021-11-16 17:58:26.102 9964-9964/com.drunkenboys.calendarun E/start: pageAdapter
2021-11-16 17:58:26.125 9964-9964/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:58:26.125 9964-9964/com.drunkenboys.calendarun E/end: 25
2021-11-16 17:58:26.125 9964-9964/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:58:26.125 9964-9964/com.drunkenboys.calendarun E/end: 24
2021-11-16 17:58:26.125 9964-9964/com.drunkenboys.calendarun E/startMonth: startMonth
2021-11-16 17:58:26.125 9964-9964/com.drunkenboys.calendarun E/end: 23
2021-11-16 17:58:26.169 9964-9964/com.drunkenboys.calendarun E/end_Month: 44
2021-11-16 17:58:26.203 9964-9964/com.drunkenboys.calendarun E/end_Month: 78
2021-11-16 17:58:26.236 9964-9964/com.drunkenboys.calendarun E/end_Month: 111 (편집됨)

### CODE REVIEW

**Review by simeunseok — APPROVED** [review]
💯

**Comment by Cha-Ji** [comment]
lineIndex라는 공유자원에 비동기적으로 접근해서 생긴 문제로 이해했는데 맞나요?

**Comment by PsPLoG** [comment]
> lineIndex라는 공유자원에 비동기적으로 접근해서 생긴 문제로 이해했는데 맞나요?

넵 맞습니다 비동기적 접근으로 타이밍 이슈가 생긴거죠!

**Review by shshksh — APPROVED** [review]
👍

**Pull request merged**
